config/routes.rb
TheDryFruitBowl::Application.routes.draw do
  
  resources :dry_fruits

  resources :contents

  resources :bowls

  resources :users
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  

  
  match 'home', :to => "static#index"
  match 'about', :to => "static#about"
  
  root :to => "static#index"
   

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :bowl_id, :dryfruit_id, :id, :quantity
  
  belongs_to :bowl, :class_name => 'Bowl', :foreign_key => "bowl_id"
  has_one :dry_fruit, :class_name => 'DryFruit', :foreign_key => "dryfruit_id"
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, :notice => 'Content was successfully created.' }
        format.json { render :json => @content, :status => :created, :location => @content }
      else
        format.html { render :action => "new" }
        format.json { render :json => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, :notice => 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :bowlid %><br />
    <%= f.number_field :bowlid %>
  </div>
  <div class="field">
    <%= f.label :dryfruitid %><br />
    <%= f.number_field :dryfruitid %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Bowlid</th>
    <th>Dryfruitid</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= content.id %></td>
    <td><%= content.bowlid %></td>
    <td><%= content.dryfruitid %></td>
    <td><%= content.quantity %></td>
    <td><%= link_to 'Show', content %></td>
    <td><%= link_to 'Edit', edit_content_path(content) %></td>
    <td><%= link_to 'Destroy', content, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @content.id %>
</p>

<p>
  <b>Bowlid:</b>
  <%= @content.bowlid %>
</p>

<p>
  <b>Dryfruitid:</b>
  <%= @content.dryfruitid %>
</p>

<p>
  <b>Quantity:</b>
  <%= @content.quantity %>
</p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>