config/routes.rb
TheDryFruitBowl::Application.routes.draw do
  
  resources :dry_fruits

  resources :contents

  resources :bowls

  resources :users
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  

  
  match 'home', :to => "static#index"
  match 'about', :to => "static#about"
  
  root :to => "static#index"
   

end

app/models/bowl.rb
class Bowl < ActiveRecord::Base
  attr_accessible :colour, :created, :description, :id, :modified, :name, :user_id
  
  belongs_to :user, :foreign_key => "user_id"
  has_many :contents
  
end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  # GET /bowls
  # GET /bowls.json
  def index
    if session[:user] == nil
      redirect_to login_url
      return
    else
      @bowls = Bowl.find(:all, :conditions => ['user_id = ?', session[:user].userid])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bowls }
    end
  end

  # GET /bowls/1
  # GET /bowls/1.json
  def show
    @bowl = Bowl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bowl }
    end
  end

  # GET /bowls/new
  # GET /bowls/new.json
  def new
    @bowl = Bowl.new
    @dry_fruits = DryFruit.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bowl }
    end
  end

  # GET /bowls/1/edit
  def edit
    @bowl = Bowl.find(params[:id])
    @dry_fruits = DryFruit.all
  end

  # POST /bowls
  # POST /bowls.json
  def create
    @bowl = Bowl.new(params[:bowl])
    
    # set the current user's id and the creation time for this bowl
    @bowl.user_id = session[:user].userid.to_i
    @bowl.created = Time.now
    
    respond_to do |format|
      if @bowl.save

        Rails.logger.info "Adding contents for bowl"
        
        params.keys.each do |param|
          if param.start_with?("input_") and (params[param] != "")            
            @bowl.contents.create(:bowl_id => @bowl.id, :dryfruit_id => param[6, 2], :quantity => params[param])  
          end
        end
        
        format.html { redirect_to bowls_path, :notice => 'Bowl was successfully created.' }
        format.json { render :json => @bowl, :status => :created, :location => @bowl }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bowl.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bowls/1
  # PUT /bowls/1.json
  def update
    @bowl = Bowl.find(params[:id])
        
    # set bowl modify time
    @bowl.modified = Time.now
    
    respond_to do |format|
      if @bowl.update_attributes(params[:bowl])
        
        Rails.logger.info "Updating Bowl Contents"
        
        # remove all contents for this bowl and add new
        @bowl.contents.delete_all("bowl_id=" + @bowl.id)
        
        params.keys.each do |param|
          if param.start_with?("input_") and (params[param] != "")            
            @bowl.contents.create(:bowl_id => @bowl.id, :dryfruit_id => param[6, 2], :quantity => params[param])  
          end
        end

        format.html { redirect_to bowls_path, :notice => 'Bowl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bowl.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bowls/1
  # DELETE /bowls/1.json
  def destroy
    @bowl = Bowl.find(params[:id])
    @bowl.destroy

    respond_to do |format|
      format.html { redirect_to bowls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bowls_helper.rb
module BowlsHelper
end

app/views/bowls/_form.html.erb
<% content_for :customscript do %>
<script type="text/javascript">

	$(function() {
		// sliderX sets value in inputX
		$(".slider").on("change", function(e, val) {
			$('#input_' + $(this).attr('id').substring(6)).val(val);
		});
		
		$(".slider").on("changed", function(e, val) {
			
			var v = 0;
			var total_energy = 0, total_fat = 0, total_protein = 0, total_carbo = 0;
			$(".slider").each(function(index) {
				// get the value from corresponding input box
				v = $('#input_' + $(this).attr('id').substring(6)).val();
				
				// ignore input that do not have valid values
				if(v != "") {
					total_energy += parseFloat(v) * parseFloat($('#input_' + $(this).attr('id').substring(6)).attr("energy"));
					total_fat += parseFloat(v) * parseFloat($('#input_' + $(this).attr('id').substring(6)).attr("fat"));
					total_protein += parseFloat(v) * parseFloat($('#input_' + $(this).attr('id').substring(6)).attr("protein"));
					total_carbo += parseFloat(v) * parseFloat($('#input_' + $(this).attr('id').substring(6)).attr("carbo"));
				}
			});
			
			$('#nutrimsg').text("You bowl contains " + total_energy.toFixed(2) + " Kcal Energy, " + total_fat.toFixed(2) + " gms Fat, " + total_protein.toFixed(2) + " gms Protein and " + total_carbo.toFixed(2) + " gms Carbohydrates. Move the sliders on the right to adjust the amount of dry fruits. Your bowls page will display detailed nutrition information.");
        })
	});

	$(document).ready(function() {
		$("#wColorPicker1").wColorPicker({
				value: $('input#bowl_colour').val(),
				theme: "white",
				mode: "click",
				showSpeed: 200,
				hideSpeed: 200,
				buttonSize: 40,
				onSelect: function(color){
					$("input#bowl_colour").css("background", color).val(color);
				}				
		});		
	});
</script>
<% end %>

<%= form_for(@bowl) do |f| %>

	<% if @bowl.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@bowl.errors.count, "error") %> prohibited this bowl from being saved:</h2>
			<ul>
				<% @bowl.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<table>
		<tr>
			<td width="40%" valign="top">
				<fieldset>
					<legend>General</legend>
					<div class="input-control text span4">
						<%= f.label :name %><br />
						<%= f.text_field :name %>
					</div>
					
					<div class="input-control text span6">
						<%= f.label :description %><br />
						<%= f.text_field :description %>
					</div>
					  
					<div>
						<%= f.label :colour %><br />
						<div id="wColorPicker1"/>
							<%= f.hidden_field :colour %>
						</div>
					</div>
					
					<div>
						<p id="nutrimsg">You bowl contains X Kcal Energy, X gms Fat, 
							X gms Protein and X gms Carbohydrates. Move the sliders on the right to adjust the amount of dry fruits.
							Your bowls page will display detailed nutrition information.
						</p> 
					</div>
				</fieldset>	
			</td>
			<td width="60%">
				<fieldset>
					<legend>Bowl Content</legend>
					<table>
						<% @dry_fruits.each do |dryfruit| %>
							<tr>
								<td width="15%">
									<%= image_tag(dryfruit.imagesmall, :size => "50x37", :title => dryfruit.name) %>	
								</td>
								<td width="70%">
									<div id="slider<%= dryfruit.id %>" class="slider" data-role="slider"/>
								</td>
								<td width="15%">
									<div class="input-control text span1 disabled">
										<input id="input_<%= dryfruit.id %>" type="text" name="input_<%= dryfruit.id %>" 
										energy="<%= number_with_precision((dryfruit.energy.to_f * dryfruit.weightpp.to_f) / 100, :precision => 2)  %>" 
										fat="<%= number_with_precision((dryfruit.fat.to_f * dryfruit.weightpp.to_f) / 100, :precision => 2) %>" 
										protein="<%= number_with_precision((dryfruit.protein.to_f * dryfruit.weightpp.to_f) / 100, :precision => 2) %>" 
										carbo="<%= number_with_precision((dryfruit.carbohydrates.to_f * dryfruit.weightpp.to_f) / 100, :precision => 2) %>" 
										readonly />
									</div>
								</td>
							</tr>
						<% end %>
					</table>
				</fieldset>
			</td>
		</tr>
	</table>

	<div class="actions">
		<%= f.submit %>
	</div>
  
<% end %>

app/views/bowls/edit.html.erb
<h1>Editing bowl</h1>

<%= render 'form' %>

<%= link_to 'Show', @bowl %> |
<%= link_to 'Back', bowls_path %>

app/views/bowls/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Your bowls are displayed here</h2>
<br/><br/>
<table>
  <tr>
  	<td>
		<ul class="accordion span10" date-role="accordion">
			<% @bowls.each do |bowl| %>
	        <li class="active">
	        	<a href="#"><%= bowl.name %></a>
	            <div>
		        	<div class="icon" style="background-color: <%= bowl.colour %>">
	                	<%= image_tag('empty-bowl.png') %>
	            	</div>	            	
	                <p><%= bowl.description %></p>
					<div class='toolbar' align="right">
				    	<%= link_to(edit_bowl_path(bowl)) do %>
							<img src='/assets/pencil1.png' title="Edit Bowl"/>
				    	<% end %> 
				    	<%= link_to(bowl, :method => :delete, :data => { :confirm => 'Are you sure?' }) do %>
							<img src='/assets/cancel1.png' title="Delete Bowl"/>
				    	<% end %>
				    </div>																	                
	            </div>
	        </li>
	        <% end %>
	    </ul>  		
  	</td>
  </tr>
</table>

<br />

<%= link_to 'New Bowl', new_bowl_path, :class => 'button' %>

app/views/bowls/new.html.erb
<h1>New bowl</h1>

<%= render 'form' %>

<%= link_to 'Back', bowls_path %>

app/views/bowls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @bowl.id %>
</p>

<p>
  <b>Userid:</b>
  <%= @bowl.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @bowl.name %>
</p>

<p>
  <b>Colour:</b>
  <%= @bowl.colour %>
</p>

<p>
  <b>Created:</b>
  <%= @bowl.created %>
</p>

<p>
  <b>Modified:</b>
  <%= @bowl.modified %>
</p>


<%= link_to 'Edit', edit_bowl_path(@bowl) %> |
<%= link_to 'Back', bowls_path %>