config/routes.rb
TheDryFruitBowl::Application.routes.draw do
  
  resources :dry_fruits

  resources :contents

  resources :bowls

  resources :users
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  

  
  match 'home', :to => "static#index"
  match 'about', :to => "static#about"
  
  root :to => "static#index"
   

end

app/models/dry_fruit.rb
class DryFruit < ActiveRecord::Base
  attr_accessible :about, :benefits, :calcium, :carbohydrates, :energy, :extra, :fat, :id, :imagelarge1, :imagelarge2, :imagelarge3, :imagesmall, :iron, :manganese, :magnesium, :name, :phosphorus, :potassium, :protein, :scientificname, :sideeffects, :sodium, :vitamin_a, :vitamin_b1, :vitamin_b12, :vitamin_b2, :vitamin_b3, :vitamin_b5, :vitamin_b6, :vitamin_b9, :vitamin_c, :vitamin_d, :vitamin_e, :vitamin_k, :zinc, :weightpp
end

app/controllers/dry_fruits_controller.rb
class DryFruitsController < ApplicationController
  
  # GET /dry_fruits
  # GET /dry_fruits.json
  def index
    @dry_fruits = DryFruit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @dry_fruits }
    end
  end

  # GET /dry_fruits/1
  # GET /dry_fruits/1.json
  def show
    @dry_fruit = DryFruit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @dry_fruit }
    end
  end

  # GET /dry_fruits/new
  # GET /dry_fruits/new.json
  def new
    @dry_fruit = DryFruit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @dry_fruit }
    end
  end

  # GET /dry_fruits/1/edit
  def edit
    @dry_fruit = DryFruit.find(params[:id])
  end

  # POST /dry_fruits
  # POST /dry_fruits.json
  def create
    @dry_fruit = DryFruit.new(params[:dry_fruit])

    respond_to do |format|
      if @dry_fruit.save
        format.html { redirect_to @dry_fruit, :notice => 'Dry fruit was successfully created.' }
        format.json { render :json => @dry_fruit, :status => :created, :location => @dry_fruit }
      else
        format.html { render :action => "new" }
        format.json { render :json => @dry_fruit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dry_fruits/1
  # PUT /dry_fruits/1.json
  def update
    @dry_fruit = DryFruit.find(params[:id])

    respond_to do |format|
      if @dry_fruit.update_attributes(params[:dry_fruit])
        format.html { redirect_to @dry_fruit, :notice => 'Dry fruit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @dry_fruit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dry_fruits/1
  # DELETE /dry_fruits/1.json
  def destroy
    @dry_fruit = DryFruit.find(params[:id])
    @dry_fruit.destroy

    respond_to do |format|
      format.html { redirect_to dry_fruits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dry_fruits_helper.rb
module DryFruitsHelper
end

app/views/dry_fruits/_form.html.erb
<%= form_for(@dry_fruit) do |f| %>
  <% if @dry_fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dry_fruit.errors.count, "error") %> prohibited this dry_fruit from being saved:</h2>

      <ul>
      <% @dry_fruit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scientificname %><br />
    <%= f.text_field :scientificname %>
  </div>
  <div class="field">
    <%= f.label :energy %><br />
    <%= f.number_field :energy %>
  </div>
  <div class="field">
    <%= f.label :fat %><br />
    <%= f.text_field :fat %>
  </div>
  <div class="field">
    <%= f.label :protein %><br />
    <%= f.text_field :protein %>
  </div>
  <div class="field">
    <%= f.label :imagesmall %><br />
    <%= f.text_field :imagesmall %>
  </div>
  <div class="field">
    <%= f.label :imagelarge1 %><br />
    <%= f.text_field :imagelarge1 %>
  </div>
  <div class="field">
    <%= f.label :imagelarge2 %><br />
    <%= f.text_field :imagelarge2 %>
  </div>
  <div class="field">
    <%= f.label :imagelarge3 %><br />
    <%= f.text_field :imagelarge3 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_a %><br />
    <%= f.text_field :vitamin_a %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b1 %><br />
    <%= f.text_field :vitamin_b1 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b2 %><br />
    <%= f.text_field :vitamin_b2 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b3 %><br />
    <%= f.text_field :vitamin_b3 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b5 %><br />
    <%= f.text_field :vitamin_b5 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b6 %><br />
    <%= f.text_field :vitamin_b6 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b9 %><br />
    <%= f.text_field :vitamin_b9 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_b12 %><br />
    <%= f.text_field :vitamin_b12 %>
  </div>
  <div class="field">
    <%= f.label :vitamin_c %><br />
    <%= f.text_field :vitamin_c %>
  </div>
  <div class="field">
    <%= f.label :vitamin_d %><br />
    <%= f.text_field :vitamin_d %>
  </div>
  <div class="field">
    <%= f.label :vitamin_e %><br />
    <%= f.text_field :vitamin_e %>
  </div>
  <div class="field">
    <%= f.label :vitamin_k %><br />
    <%= f.text_field :vitamin_k %>
  </div>
  <div class="field">
    <%= f.label :carbohydrates %><br />
    <%= f.text_field :carbohydrates %>
  </div>
  <div class="field">
    <%= f.label :calcium %><br />
    <%= f.text_field :calcium %>
  </div>
  <div class="field">
    <%= f.label :iron %><br />
    <%= f.text_field :iron %>
  </div>
  <div class="field">
    <%= f.label :magnesium %><br />
    <%= f.text_field :magnesium %>
  </div>
  <div class="field">
    <%= f.label :manganese %><br />
    <%= f.text_field :manganese %>
  </div>
  <div class="field">
    <%= f.label :phosphorus %><br />
    <%= f.text_field :phosphorus %>
  </div>
  <div class="field">
    <%= f.label :potassium %><br />
    <%= f.text_field :potassium %>
  </div>
  <div class="field">
    <%= f.label :sodium %><br />
    <%= f.text_field :sodium %>
  </div>
  <div class="field">
    <%= f.label :zinc %><br />
    <%= f.text_field :zinc %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :benefits %><br />
    <%= f.text_area :benefits %>
  </div>
  <div class="field">
    <%= f.label :sideeffects %><br />
    <%= f.text_area :sideeffects %>
  </div>
  <div class="field">
    <%= f.label :extra %><br />
    <%= f.text_field :extra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dry_fruits/edit.html.erb
<h1>Edit <%= @dry_fruit.name %></h1>
<br/> You can use this page to improve or change information related to a dry fruit.
<br/>
<%= render 'form' %>

<%= link_to 'Show', @dry_fruit %> |
<%= link_to 'Back', dry_fruits_path %>

app/views/dry_fruits/index.html.erb
<h1 align="center">Dry Fruits Catalog</h1>
<br/><br/>
<div class="clearfix" style="margin: 0px 100px 100px 100px">
	<% @dry_fruits.each do |dryfruit| %>
		<a href="dry_fruits/<%= dryfruit.id %>">
		<div class="tile double-vertical bg-color-white border-color-blueLight">
	        <div class="tile-content fg-color-blue">
	        	<%= image_tag(dryfruit.imagesmall) %>
				<center><h3><%= dryfruit.name %></h3>
				<hr/>
				<p>The scientific name of this dry fruit is
				<i><%= dryfruit.scientificname %></i>. 100 gms serving of this dry fruit provides  
				<%= dryfruit.energy %> Kcal of energy, <%= dryfruit.fat %> gms fat
				and <%= dryfruit.protein %> gms protein.</p></center>        	
	        </div>	
		</div>
		</a>
	<% end %>
</div>
<br/><br/>
<%= link_to 'New Dryfruit', new_dry_fruit_path, :class => 'button' %>

app/views/dry_fruits/new.html.erb
<h1>New dry_fruit</h1>

<%= render 'form' %>

<%= link_to 'Back', dry_fruits_path %>

app/views/dry_fruits/show.html.erb
<center><h2><%= @dry_fruit.name %> (<%= @dry_fruit.scientificname %>)</h2></center>

<table>
	<tbody>
		<tr>
			<td width="25%" align="center" valign="top">
				<table class="bordered striped">
					<tbody>
						<tr>
							<td>Energy</td>
							<td><%= @dry_fruit.energy %> kcal</td>	
						</tr>
						<tr>
							<td>Fat</td>
				  			<td><%= @dry_fruit.fat %> gms</td>	
						</tr>
						<tr>
				  			<td>Protein</td>
				  			<td><%= @dry_fruit.protein %> gms</td>			
						</tr>
						<tr>
				  			<td>Carbohydrates</td>
				  			<td><%= @dry_fruit.carbohydrates %> gms</td>			
						</tr>
						<tr>
				  			<td>Calcium</td>
				  			<td><%= @dry_fruit.calcium %> mg</td>			
						</tr>
						<tr>
				  			<td>Iron</td>
				  			<td><%= @dry_fruit.iron %> mg</td>			
						</tr>
						<tr>
				  			<td>Manganese</td>
				  			<td><%= @dry_fruit.manganese %> mg</td>			
						</tr>
						<tr>
				  			<td>Magnesium</td>
				  			<td><%= @dry_fruit.magnesium %> mg</td>			
						</tr>
						<tr>
				  			<td>Phosphorus</td>
				  			<td><%= @dry_fruit.phosphorus %> mg</td>			
						</tr>
						<tr>
				  			<td>Potassium</td>
				  			<td><%= @dry_fruit.potassium %> mg</td>			
						</tr>
						<tr>
				  			<td>Sodium</td>
				  			<td><%= @dry_fruit.sodium %> mg</td>			
						</tr>
						<tr>
				  			<td>Zinc</td>
				  			<td><%= @dry_fruit.zinc %> mg</td>			
						</tr>						
					</tbody>
				</table>    				
			</td>
			<td width="50%" align="center">
				<div class="span5">
					<div class="carousel span5" style="height: 300px;" data-role="carousel" data-param-effect="fade" data-param-direction="left" data-param-period="3000" data-param-markers="on">
					    <div class="slides">
					        <div class="slide image" id="slide4">
					            <img src="/assets/<%= @dry_fruit.imagelarge1 %>" />
					        </div>
					        <div class="slide image" id="slide5">
					            <img src="/assets/<%= @dry_fruit.imagelarge2 %>" />
					        </div>
					    </div>
					</div>
					</div>
				</div>				
			</td>
			<td width="25%" align="center" valign="top">
				<table class="bordered striped">
					<tbody>
						<tr>
							<td>Vitamin A</td>
							<td><%= @dry_fruit.vitamin_a %> IU</td>
						</tr>
						<tr>
							<td>Vitamin B1</td>
							<td><%= @dry_fruit.vitamin_b1 %> mg</td>			
						</tr>		
						<tr>
							<td>Vitamin B2</td>
							<td><%= @dry_fruit.vitamin_b2 %> mg</td>	
						</tr>
						<tr>
							<td>Vitamin B3</td>
				  			<td><%= @dry_fruit.vitamin_b3 %> mg</td>	
						</tr>
						<tr>
				  			<td>Vitamin B5</td>
				  			<td><%= @dry_fruit.vitamin_b5 %> mg</td>			
						</tr>
						<tr>
				  			<td>Vitamin B6</td>
				  			<td><%= @dry_fruit.vitamin_b6 %> mg</td>			
						</tr>
						<tr>
				  			<td>Vitamin B9</td>
				  			<td><%= @dry_fruit.vitamin_b9 %> ug</td>			
						</tr>
						<tr>
				  			<td>Vitamin B12</td>
				  			<td><%= @dry_fruit.vitamin_b12 %> ug</td>			
						</tr>
						<tr>
				  			<td>Vitamin C</td>
				  			<td><%= @dry_fruit.vitamin_c %> mg</td>			
						</tr>
						<tr>
				  			<td>Vitamin D</td>
				  			<td><%= @dry_fruit.vitamin_d %> mg</td>			
						</tr>
						<tr>
				  			<td>Vitamin E</td>
				  			<td><%= @dry_fruit.vitamin_e %> mg</td>			
						</tr>
						<tr>
				  			<td>Vitamin K</td>
				  			<td><%= @dry_fruit.vitamin_k %> ug</td>			
						</tr>						
					</tbody>
				</table>    								
			</td>
		</tr>
		<tr>
			<td colspan="3">
				<h3>About</h3>
				<p><%= @dry_fruit.about %></p>
			</td>
		</tr>		
		<tr>
			<td colspan="3">
				<h3>Benefits</h3>
				<p><%= @dry_fruit.benefits %></p>
			</td>
		</tr>
		<tr>
			<td colspan="3">
				<h3>Side Effects</h3>
				<p><%= @dry_fruit.sideeffects %></p>
			</td>
		</tr>		
	</tbody>
</table>

<div align="right">** Servings per 100 gm, ** Source: Wikipedia.org</div>

<%= link_to 'Edit', edit_dry_fruit_path(@dry_fruit) %> |
<%= link_to 'Back', dry_fruits_path %>