config/routes.rb
TheDryFruitBowl::Application.routes.draw do
  
  resources :dry_fruits

  resources :contents

  resources :bowls

  resources :users
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  

  
  match 'home', :to => "static#index"
  match 'about', :to => "static#about"
  
  root :to => "static#index"
   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Dry Fruit Bowl Project</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :customscript %>
</head>
<body style="margin: 20px 20px 20px 20px; background-color: white">
	<table>
		<tbody>
			<tr>
				<td width="80%">
					<div class="nav-bar bg-color-white">
						<div class="nav-bar-inner">
							<span class="element"><%= link_to 'Home', { :controller => 'static', :action => 'index'} %></span>
					        <span class="divider"></span>
					        <span class="element"><%= link_to 'Catalog', { :controller => 'dry_fruits', :action => 'index'} %></span>
					        <span class="divider"></span>
							
							<% if session[:user] == nil %>
					        	<span class="element"><%= link_to 'My Bowls', { :controller => 'bowls', :action => 'index'} %></span>
					        <% else %>
								<ul class="menu">
									<li data-role="dropdown">
										<a href="#"><b><%= session[:user].firstname %></b></a>
										<ul class="dropdown-menu">
											<li>
												<%= link_to 'My Bowls', bowls_path %>
											</li>
											<li>
												<%= link_to 'Edit Profile', edit_user_path(session[:user].userid) %>
											</li>
											<li>
												<%= link_to 'Logout', logout_path, :method => :delete %>
											</li>
											<% if session[:user].role == 0 %>
												<li class="divider"></li>
												<li>
													<%= link_to 'Users', users_path %>
												</li>											
											<% end %>
										</ul>
									</li>
								</ul>
					        <% end %>	        
				        </div>
					</div>					
				</td>
				<td width="20%" align="right">
					<%= link_to 'Release 0.1 Neptune', "#", :id => "modal", :remote => true, :class => 'button bg-color-orange' %>					        
				</td>
			</tr>
		</tbody>
	</table>

<%= yield %>

</body>
</html>